config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
     resources :appointments
   end
  root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor, class_name: "User", foreign_key: "doctor_id"
  belongs_to :patient, class_name: "User", foreign_key: "patient_id"
  has_one :appointment_record, dependent: :destroy
end

app/models/appointment_record.rb
class AppointmentRecord < ApplicationRecord
	belongs_to :appointment
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum roles: { admin: 0, patient: 1, doctor: 2 }
  
  has_many :appointment_records, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :authenticate_user!
     before_action :configure_permitted_parameters, if: :devise_controller?


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :role)}
    end
end

app/controllers/appointment_records_controller.rb
class AppointmentRecordsController < ApplicationController
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	def new
		binding.pry
		@user = current_user
		# @appointment = @user
	end


	def create

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_records_helper.rb
module AppointmentRecordsHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointments/new.html.erb
<%= form_for @appointment, :as => :appointment, :url => sign_in_path(@user) do |f| %>

    <%= f.select(:doctor, User.where(role: "doctor").map { |w| [w.id, w.email] }, {}, { :class => 'my_style_class' }) %>  

<% end %>

app/views/home/index.html.erb
You have successfully login

<%=link_to "New Appointment", new_user_appointment_path(current_user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <% if  user_signed_in? %>
   <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %> 

</html>